services:

  mvp_server:
    container_name: MvpServer

    build:
      context: .
      dockerfile: ./docker/development/server/Dockerfile

    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development

    volumes:
      - ./server/:/server_source/

    ports:
      - 8001:8000

    command: bash /start.sh

    depends_on:
      - mvp_database

  mvp_database:
    image: postgres:15.1-alpine
    container_name: MvpDatabase

    volumes:
      - dev_db_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

    ports:
      - 5433:5432

volumes:
  dev_db_data:
